version: "3"
services:
  chrome:
    image: packages.schroders.com/docker/selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"

  edge:
    image: packages.schroders.com/docker/selenium/node-edge:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"

  firefox:
    image: packages.schroders.com/docker/selenium/node-firefox:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"

  opera:
    image: packages.schroders.com/docker/selenium/node-opera:4.0.0-beta-3-prerelease-20210321
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"

  selenium-hub:
    image: packages.schroders.com/docker/selenium/hub:4.0.0-beta-3-prerelease-20210321
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
